### ISSUE TITLE
Target audience of the white paper?

### ISSUE THREAD

**Issue by yymao** [lsstdarkmatter/dark-matter-paper#15]
Who are the intended target audience of this white paper? Particle physicists? Other astronomers not working on dark matter? People working on direct/indirect detection? Funding agencies? Any other thoughts?

How should we format our white paper to better serve our target audience?

**Comment by lmoustakas** [comment]
There was a comment yesterday that calling the dark matter insights from LSST a "springboard" for the community's deeper understanding of the fundamental nature of dark matter, would be a positive way to state the focus of the work.  Giving this context might help give this LSST-oriented white paper appeal to a broader community.

**Comment by lmoustakas** [comment]
There's an opportunity for this white paper to help re-introduce dark matter to the community as a topic worth focusing on in the future.  With the 2020 astrophysics decadal coming up, the white paper could not only showcase LSST's capability, but also what will be needed beyond LSST.

**Comment by kadrlica** [comment]
Based on the discussion, it seems reasonable to target a concise, high-level paper (~10 pages) that would summarize the dark matter program involving LSST. This white paper would contain the key plots discussed in #14 with some brief explanation. The details of generating these plots would be distributed in supporting publications (ideally refereed publications, but potentially supporting white papers).

**Comment by kadrlica** [comment]
This white paper has targeted the DOE audience. A short follow-up is planned for Astro2020.
