### ISSUE TITLE
Constraining PBH with LSST Stellar Dynamics

### ISSUE THREAD

**Issue by sbird** [lsstdarkmatter/dark-matter-paper#4]
Primordial black holes can affect the dynamics of stellar systems in dwarf galaxies. The effects can be used to constrain the population, whether the population is massive (e.g., LIGO-size black holes) or sub-solar mass. We are interested to find out what the additional reach of LSST can do to constraints on a PBH population.

**Comment by wadawson** [comment]
I suggest that we merge #4 and #8.

**Comment by sbird** [comment]
Closing and let's take it to #8.
